version: '2'
plugins:
  tslint:
    enabled: true
    config: tslint.json
exclude_patterns:
- '**/*.test.ts'
- 'dist/'
- 'node_modules/'
- 'coverage/'
checks:
  file-lines:
    config:
      threshold: 350
