version: '2'
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 65
      
plugins:
  tslint:
    enabled: false
    channel: beta
exclude_patterns:
- '**/*.test.ts'
- 'dist/'
- 'node_modules/'
- 'coverage/'
checks:
  file-lines:
    config:
      threshold: 350
