engines:
  tslint:
    enabled: false
    channel: beta
ratings:
  paths:
  - 'lib/**/*'
  - '**.ts'
exclude_paths:
- dist
- node_modules
- coverage
exclude_patterns:
- '**.test.ts'
checks:
  file-lines:
    config:
      threshold: 350
