engines:
  tslint:
    enabled: true
    channel: beta
ratings:
  paths:
  - 'lib/**/*'
  - '**.ts'
exclude_paths:
- dist
- node_modules
- coverage
checks:
  file-lines:
    config:
      threshold: 350
